/**
 * Where the Python model runtimes live, and how their installers are launched.
 *
 * Windows keeps each venv + model cache NEXT TO the scripts (tts-server/runtime*): the
 * user profile on the dev machine is EFS-encrypted and MSIX-virtualized, which breaks pip
 * and makes two processes disagree about %APPDATA%.
 *
 * macOS cannot do that: a packaged app's scripts sit inside the signed, read-only
 * `.app` bundle, and writing a 1GB venv there would break the code signature. None of
 * the Windows profile problems exist on macOS, so the runtimes go under userData
 * (~/Library/Application Support/Aloud Reader/tts-server/), which also survives
 * reinstalling or moving the app.
 */
import { app } from 'electron';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

export const IS_WIN = process.platform === 'win32';

export type RuntimeName = 'runtime' | 'runtime-voxcpm';

export const runtimeDir = (scriptsDir: string, name: RuntimeName): string =>
  IS_WIN ? path.join(scriptsDir, name) : path.join(app.getPath('userData'), 'tts-server', name);

export const venvPython = (runtime: string): string =>
  IS_WIN ? path.join(runtime, 'venv', 'Scripts', 'python.exe') : path.join(runtime, 'venv', 'bin', 'python');

/** Installer script name for this platform (`install` -> install.bat / install.sh). */
export const scriptFile = (base: string): string => `${base}${IS_WIN ? '.bat' : '.sh'}`;

/**
 * Open the installer in a visible terminal so the user can watch pip / model download
 * progress. On macOS a `.command` file is what Finder hands to Terminal.app without any
 * Automation permission prompt, so we write a tiny one that runs the real script.
 */
export function openInstaller(scriptsDir: string, base: string, name: RuntimeName, title: string): void {
  const script = path.join(scriptsDir, scriptFile(base));
  if (!fs.existsSync(script)) throw new Error(`找不到安装脚本：${script}`);
  const target = runtimeDir(scriptsDir, name);

  if (IS_WIN) {
    spawn('cmd', ['/c', 'start', `"${title}"`, 'cmd', '/k', script, target], {
      cwd: scriptsDir,
      detached: true,
      stdio: 'ignore',
    }).unref();
    return;
  }

  fs.mkdirSync(target, { recursive: true });
  const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;
  const launcher = path.join(path.dirname(target), `${base}.command`);
  fs.writeFileSync(
    launcher,
    `#!/bin/bash\n# ${title} — generated by Aloud Reader\nexec /bin/bash ${q(script)} ${q(target)}\n`,
    { mode: 0o755 },
  );
  fs.chmodSync(launcher, 0o755);
  if (process.platform === 'darwin') {
    spawn('open', ['-a', 'Terminal', launcher], { detached: true, stdio: 'ignore' }).unref();
  } else {
    spawn('x-terminal-emulator', ['-e', launcher], { detached: true, stdio: 'ignore' }).unref();
  }
}
